version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  ai_engine:
    build: ./ai_engine
    volumes:
      - ./ai_engine:/ai

  frontend:
    build: ./frontend
    ports:
      - "3000:80"   # Flutter Web serve qua nginx

  postgres:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: english_ai

volumes:
  postgres_data:
